server {
    listen 80;

    #servir el frontend
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    #redirigir peticiones de ventas al backend
    location /api/v1/ventas {
        proxy_pass http://back-ventas:8080;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    #redirigir peticiones de despachos al backend
    location /api/v1/despachos {
        proxy_pass http://back-despachos:8081;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
